### ISSUE TITLE
Compile error when `echoes_profiling` is set

### ISSUE THREAD

**Issue by UncertainProd** [player-03/echoes#15]
When I compile a project and set the `echoes_profiling` flag, it gives a build error in 
System.hx:193: characters 38-52 : Float should be Int

From the code:
```haxe
public function getStatistics():SystemDetails {
		return {
			name: Std.string(this)
			#if echoes_profiling , deltaTime: __updateTime__ #end
		};
}
```
It looks like `__updateTime__` is a Float while `deltaTime` is an Int

**Comment by player-03** [comment]
Thanks for catching this!
