### ISSUE TITLE
Using component classes with alias leads to compile error

### ISSUE THREAD

**Issue by Dreaded-Gnu** [player-03/echoes#18]
Hello,
don't know whether that's addressable, but when you're importing a component class with an alias by using e.g. `import thirdparty.ecs.component.Position as PositionComponent;`, it results for me in the following compile error:

```
source/Main.hx:116: characters 5-79 : Type not found : PositionComponent
export/linux/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
```

**Comment by player-03** [comment]
I'll look into this when I have a chance.

**Comment by player-03** [comment]
Should be fixed, let me know if not.

**Comment by Dreaded-Gnu** [comment]
Tried it and fix worked out well
