### ISSUE TITLE
Haxe compiler server issues with macros

### ISSUE THREAD

**Issue by zommerfelds** [player-03/echoes#6]
Do you use vscode with the Haxe compilation server mode? I had a lot of ramp up issues when using Echoes because macro issues would often get the server into a permanent broken state.

Now I trained myself to restart the Haxe compilation server whenever I see huge cryptic compiler errors :)

Just wanted to point this out in case anyone searches for the this. It's probably an issue in Haxe, but hard to repro. But maybe there are things this repo could do to avoid falling into those issues.

Sorry that I don't have a repro case right now.

**Comment by player-03** [comment]
I get those too, occasionally. I think I've managed to fix some of them, but the fact that they're so rare makes them hard to track down.

**Comment by onehundredfeet** [comment]
These are really hard to fix with this ECS.  I've fixed a few as well and try to stay on top of them when I add new things.

**Comment by player-03** [comment]
It's been a couple months since my last big macro rewrite, and I haven't seen the error at all. I think maybe it's fixed.

I've been seeing a new issue in its place, though. The completion server sometimes locks up when compile errors are detected. Not sure if this new one is Echoes-related at all, but it's every bit as annoying.

**Comment by NitroPlum** [comment]
I'm also seeing this. It seems like the smallest issue causes my language server to crash.

**Comment by player-03** [comment]
Not just me, then. Ok, I'll try to make time to work on this.

**Comment by player-03** [comment]
Ugh, this is proving difficult. I've opened an issue [here](https://github.com/HaxeFoundation/haxe/issues/11456) in hopes that someone on the Haxe team knows what's going on.

**Comment by player-03** [comment]
I finally found [a workaround](https://github.com/player-03/echoes/commit/e6068438b783eb65fb462af827d0165ea75ede52)!

I've only tested it on my computer, but it should work anywhere. Let me know if not.

**Comment by zommerfelds** [comment]
Thanks for the investigation, this looked tricky to debug!

**Comment by player-03** [comment]
Still haven't found the root of it, but I think that's for the Haxe devs to deal with. In the meantime, we have the workaround.
