### ISSUE TITLE
There are some issues with abstract types

### ISSUE THREAD

**Issue by rayloi777** [player-03/echoes#8]
There are some issues with abstract types 

<img width="934" alt="螢幕截圖 2023-03-30 上午3 34 31" src="https://user-images.githubusercontent.com/13784700/228648937-e05f8f12-c70a-4927-9993-d3e13fc8d909.png">

**Comment by player-03** [comment]
Generally in situations like this, it's easiest to write `typedef Speed = Float`.

If it must be an abstract (usually because you want to add instance functions), then you'll need a [`@:to` function](https://haxe.org/manual/types-abstract-implicit-casts.html) that returns `Int`.

**Comment by rayloi777** [comment]
Is Work ! Thanks for your help :)

**Comment by player-03** [comment]
I should also mention, it's cool to see someone using this! Hope things are going smoothly.
